-d G:\Git\oscilloscope-fpga\fpga_project\impl\gwsynthesis\fpga_project.vg
-p GW1N-1-QFN48-6
-pn GW1N-LV1QN48C6/I5
-cst G:\Git\oscilloscope-fpga\fpga_project\src\fpga_project.cst
-cfg G:\Git\oscilloscope-fpga\fpga_project\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
